
services:
  react-app:
    build:
      context: ../react-crash-course
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/my_restaurant?allowPublicKeyRetrieval=TRUE&autoReconnect=TRUE&useSSL=FALSE
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_PLATFORM: mysql
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "rootpass"
   
    networks:
      - app-network
 
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: my_restaurant
    # Bind to localhost  
   
    networks:
      - app-network

networks:
  app-network: